# This is a basic workflow to help you get started with Actions

name: on_tag

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: launch nginx
        run: docker run --name nginx -v $(pwd):/usr/share/nginx/html:ro -dP nginx      
      - name: get nginx port
        run: echo "nginx_port=$(docker container ls | grep nginx | sed 's/.*0\.0\.0\.0:\([0-9]*\)-.*/\1/')" >> $GITHUB_ENV
      - name: build image
        run: docker buildx build --network host --build-arg PORT=${{ env.nginx_port }} .
